# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from xmanager_cloud.dashboard_service.proto import dashboard_service_pb2 as xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2
from xmanager_cloud.dashboard_service.proto import messages_pb2 as xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xmanager_cloud/dashboard_service/proto/dashboard_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DashboardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDashboard = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/CreateDashboard',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.CreateDashboardRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.FromString,
                _registered_method=True)
        self.GetDashboard = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/GetDashboard',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetDashboardRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.FromString,
                _registered_method=True)
        self.ListDashboards = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/ListDashboards',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListDashboardsRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListDashboardsResponse.FromString,
                _registered_method=True)
        self.UpdateDashboard = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/UpdateDashboard',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.UpdateDashboardRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.FromString,
                _registered_method=True)
        self.DeleteDashboard = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/DeleteDashboard',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.DeleteDashboardRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateChart = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/CreateChart',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.CreateChartRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.FromString,
                _registered_method=True)
        self.GetChart = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/GetChart',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetChartRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.FromString,
                _registered_method=True)
        self.GetChartData = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/GetChartData',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetChartDataRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.ChartData.FromString,
                _registered_method=True)
        self.ListCharts = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/ListCharts',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListChartsRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListChartsResponse.FromString,
                _registered_method=True)
        self.UpdateChart = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/UpdateChart',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.UpdateChartRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.FromString,
                _registered_method=True)
        self.DeleteChart = channel.unary_unary(
                '/cloud.xmanager.v1.DashboardService/DeleteChart',
                request_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.DeleteChartRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class DashboardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDashboard(self, request, context):
        """The whole request is the body rather than just `dashboard`, because `charts` has to travel with
        it: a repeated message cannot be expressed as a query parameter, and the point of the field is
        that the charts are created in the same transaction as the dashboard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDashboards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChartData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCharts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDashboard,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.CreateDashboardRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.SerializeToString,
            ),
            'GetDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboard,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetDashboardRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.SerializeToString,
            ),
            'ListDashboards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDashboards,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListDashboardsRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListDashboardsResponse.SerializeToString,
            ),
            'UpdateDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDashboard,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.UpdateDashboardRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.SerializeToString,
            ),
            'DeleteDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDashboard,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.DeleteDashboardRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateChart': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChart,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.CreateChartRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.SerializeToString,
            ),
            'GetChart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChart,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetChartRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.SerializeToString,
            ),
            'GetChartData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChartData,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetChartDataRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.ChartData.SerializeToString,
            ),
            'ListCharts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCharts,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListChartsRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListChartsResponse.SerializeToString,
            ),
            'UpdateChart': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChart,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.UpdateChartRequest.FromString,
                    response_serializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.SerializeToString,
            ),
            'DeleteChart': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChart,
                    request_deserializer=xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.DeleteChartRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.xmanager.v1.DashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.xmanager.v1.DashboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DashboardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/CreateDashboard',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.CreateDashboardRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/GetDashboard',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetDashboardRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDashboards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/ListDashboards',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListDashboardsRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListDashboardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/UpdateDashboard',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.UpdateDashboardRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Dashboard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/DeleteDashboard',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.DeleteDashboardRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/CreateChart',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.CreateChartRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/GetChart',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetChartRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChartData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/GetChartData',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.GetChartDataRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.ChartData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCharts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/ListCharts',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListChartsRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.ListChartsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/UpdateChart',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.UpdateChartRequest.SerializeToString,
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_messages__pb2.Chart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.DashboardService/DeleteChart',
            xmanager__cloud_dot_dashboard__service_dot_proto_dot_dashboard__service__pb2.DeleteChartRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
