# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from xmanager_cloud.xid_service.proto import api_pb2 as xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2
from xmanager_cloud.xid_service.proto import messages_pb2 as xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xmanager_cloud/xid_service/proto/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XidServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetXidEntry = channel.unary_unary(
                '/cloud.xmanager.v1.XidService/GetXidEntry',
                request_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.GetXidEntryRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.FromString,
                _registered_method=True)
        self.CheckUserAuthorization = channel.unary_unary(
                '/cloud.xmanager.v1.XidService/CheckUserAuthorization',
                request_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CheckUserAuthorizationRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CheckUserAuthorizationResponse.FromString,
                _registered_method=True)
        self.ListXidEntries = channel.unary_unary(
                '/cloud.xmanager.v1.XidService/ListXidEntries',
                request_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesResponse.FromString,
                _registered_method=True)
        self.SearchXidEntries = channel.unary_unary(
                '/cloud.xmanager.v1.XidService/SearchXidEntries',
                request_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesResponse.FromString,
                _registered_method=True)
        self.CreateXidEntry = channel.unary_unary(
                '/cloud.xmanager.v1.XidService/CreateXidEntry',
                request_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CreateXidEntryRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.FromString,
                _registered_method=True)
        self.UpdateXidEntry = channel.unary_unary(
                '/cloud.xmanager.v1.XidService/UpdateXidEntry',
                request_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.UpdateXidEntryRequest.SerializeToString,
                response_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.FromString,
                _registered_method=True)


class XidServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetXidEntry(self, request, context):
        """AIP-131 compliant Get API call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserAuthorization(self, request, context):
        """A utility API call to authorize a user to act on a given XID. This is
        intended to be used by the XManager client libraries without calling
        GetXidEntry spuriously.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListXidEntries(self, request, context):
        """AIP-132 compliant List API call. Data returned from this method is strongly
        consistent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchXidEntries(self, request, context):
        """Search API call that mimics AIP-132 List behavior for searching. Data
        returned from this method is at most 15 seconds stale.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateXidEntry(self, request, context):
        """AIP-133 compliant Create API call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateXidEntry(self, request, context):
        """AIP-134 compliant Update API call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XidServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetXidEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetXidEntry,
                    request_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.GetXidEntryRequest.FromString,
                    response_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.SerializeToString,
            ),
            'CheckUserAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserAuthorization,
                    request_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CheckUserAuthorizationRequest.FromString,
                    response_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CheckUserAuthorizationResponse.SerializeToString,
            ),
            'ListXidEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListXidEntries,
                    request_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesRequest.FromString,
                    response_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesResponse.SerializeToString,
            ),
            'SearchXidEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchXidEntries,
                    request_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesRequest.FromString,
                    response_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesResponse.SerializeToString,
            ),
            'CreateXidEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateXidEntry,
                    request_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CreateXidEntryRequest.FromString,
                    response_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.SerializeToString,
            ),
            'UpdateXidEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateXidEntry,
                    request_deserializer=xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.UpdateXidEntryRequest.FromString,
                    response_serializer=xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.xmanager.v1.XidService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.xmanager.v1.XidService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XidService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetXidEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.XidService/GetXidEntry',
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.GetXidEntryRequest.SerializeToString,
            xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.XidService/CheckUserAuthorization',
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CheckUserAuthorizationRequest.SerializeToString,
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CheckUserAuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListXidEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.XidService/ListXidEntries',
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesRequest.SerializeToString,
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchXidEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.XidService/SearchXidEntries',
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesRequest.SerializeToString,
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.ListXidEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateXidEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.XidService/CreateXidEntry',
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.CreateXidEntryRequest.SerializeToString,
            xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateXidEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.xmanager.v1.XidService/UpdateXidEntry',
            xmanager__cloud_dot_xid__service_dot_proto_dot_api__pb2.UpdateXidEntryRequest.SerializeToString,
            xmanager__cloud_dot_xid__service_dot_proto_dot_messages__pb2.XidEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
