# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xmanager_cloud/xid_service/proto/messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'xmanager_cloud/xid_service/proto/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/xmanager_cloud/xid_service/proto/messages.proto\x12\x11\x63loud.xmanager.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x02\n\x08XidEntry\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x08\x12\x14\n\x07\x63reator\x18\x02 \x01(\tB\x03\xe0\x41\x03\x12\x34\n\x0b\x63reate_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03\x12\x34\n\x0bupdate_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03\x12\x39\n\x06origin\x18\x05 \x01(\x0b\x32$.cloud.xmanager.v1.OriginatingSystemB\x03\xe0\x41\x05\x12-\n\x04\x61\x63ls\x18\x06 \x01(\x0b\x32\x1a.cloud.xmanager.v1.XidAclsB\x03\xe0\x41\x02\x12\x17\n\nparent_xid\x18\x07 \x01(\tB\x03\xe0\x41\x01:M\xea\x41J\n&cloud.xmanager.googleapis.com/XidEntry\x12\nxids/{xid}*\nxidEntries2\x08xidEntry\"\x8e\x03\n\x07XidAcls\x12/\n\x06owners\x18\x01 \x03(\x0b\x32\x1f.cloud.xmanager.v1.XidAcls.Role\x12\x30\n\x07writers\x18\x02 \x03(\x0b\x32\x1f.cloud.xmanager.v1.XidAcls.Role\x12\x30\n\x07readers\x18\x03 \x03(\x0b\x32\x1f.cloud.xmanager.v1.XidAcls.Role\x1a\xa3\x01\n\x04Role\x12\x0e\n\x04user\x18\x01 \x01(\tH\x00\x12\x0f\n\x05group\x18\x02 \x01(\tH\x00\x12\x19\n\x0fservice_account\x18\x03 \x01(\tH\x00\x12\x10\n\x06\x64omain\x18\x04 \x01(\tH\x00\x12!\n\x17\x61ll_authenticated_users\x18\x05 \x01(\x08H\x00\x12\x1d\n\x13inherit_from_parent\x18\x06 \x01(\x08H\x00\x42\x0b\n\tprincipal\"H\n\x08RoleType\x12\x19\n\x15ROLE_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06READER\x10\x01\x12\n\n\x06WRITER\x10\x02\x12\t\n\x05OWNER\x10\x03\"%\n\x11OriginatingSystem\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\tB\x02P\x01\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xmanager_cloud.xid_service.proto.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_XIDENTRY'].fields_by_name['name']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['name']._serialized_options = b'\340A\010'
  _globals['_XIDENTRY'].fields_by_name['creator']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['creator']._serialized_options = b'\340A\003'
  _globals['_XIDENTRY'].fields_by_name['create_time']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['create_time']._serialized_options = b'\340A\003'
  _globals['_XIDENTRY'].fields_by_name['update_time']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['update_time']._serialized_options = b'\340A\003'
  _globals['_XIDENTRY'].fields_by_name['origin']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['origin']._serialized_options = b'\340A\005'
  _globals['_XIDENTRY'].fields_by_name['acls']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['acls']._serialized_options = b'\340A\002'
  _globals['_XIDENTRY'].fields_by_name['parent_xid']._loaded_options = None
  _globals['_XIDENTRY'].fields_by_name['parent_xid']._serialized_options = b'\340A\001'
  _globals['_XIDENTRY']._loaded_options = None
  _globals['_XIDENTRY']._serialized_options = b'\352AJ\n&cloud.xmanager.googleapis.com/XidEntry\022\nxids/{xid}*\nxidEntries2\010xidEntry'
  _globals['_XIDENTRY']._serialized_start=164
  _globals['_XIDENTRY']._serialized_end=533
  _globals['_XIDACLS']._serialized_start=536
  _globals['_XIDACLS']._serialized_end=934
  _globals['_XIDACLS_ROLE']._serialized_start=697
  _globals['_XIDACLS_ROLE']._serialized_end=860
  _globals['_XIDACLS_ROLETYPE']._serialized_start=862
  _globals['_XIDACLS_ROLETYPE']._serialized_end=934
  _globals['_ORIGINATINGSYSTEM']._serialized_start=936
  _globals['_ORIGINATINGSYSTEM']._serialized_end=973
# @@protoc_insertion_point(module_scope)
